### ISSUE TITLE
Update translations for v0.4

### ISSUE THREAD

**Issue by stephanlachnit** [libratbag/piper#459]
Ubuntu 20.04 LTS is on it's way and we plan to release a new piper version before the merge window on the 27th February. Since some translations are a little bit older, so I created this issue to ping all past translators to ask them for help.
If you want to update a translation, please do this before the 13th February so the release will safely land.

- [ ] Belarusian: @dastier
- [x] Bulgarian: @lyubomirv - #466
- [x] German: @whot @stephanlachnit - #460
- [ ] Spanish: @xoascf
- [x] French: @RedBusters @Funeoz @bentiss - #463
- [x] Croatian: @muzena - #461
- [ ] Dutch: @Hjdskes
- [x] Polish: @piotrdrag - #462
- [x] Chinese: @s8321414 - #464
- [x] Swedish: @AsavarTzeth @stephanlachnit - #465
- [ ] Brazilian Portugese: @RockyTV
- [x] Italian: Crowbar90 - #467

**Comment by s8321414** [comment]
I can't see any new strings in zh_TW...

**Comment by muzena** [comment]
> I can't see any new strings in zh_TW...

Read README.md file in po folder
