### ISSUE TITLE
v0.5 release

### ISSUE THREAD

**Issue by stephanlachnit** [libratbag/piper#518]
libratbag 0.14 got released, so it's time to update the translations for a new Piper release. No string related PRs will be merged until the new release, new svgs etc are still fine though. /cc @FFY00

I would give 1 week for the translations, if anyone needs more time just say it. Most translations don't need to be updated if they have already been updated for Piper 0.4, there hasn't been a string related change since then.

As always, I ping all prior translators:
- [x] Belarusian: @dastier
- [x] Bulgarian: @lyubomirv
- [x] German: @whot @stephanlachnit @eppixx
- [ ] Spanish: @xoascf
- [x] French: @RedBusters @Funeoz @bentiss - #519
- [x] Croatian: @muzena - #522
- [ ] Dutch: @Hjdskes @Vistaus
- [x] Polish: @piotrdrag
- [x] Chinese: @s8321414
- [x] Swedish: @AsavarTzeth @stephanlachnit - #520
- [x] Brazilian Portugese: @RockyTV - #521
- [ ] Italian: @Crowbar90

**Comment by FFY00** [comment]
Sorry for the spam. A new libratbag release doesn't necessarily mean new piper release, in this case, I think it's fine since there have been some changes to `data`.

**Comment by s8321414** [comment]
No new string for zh_TW :smiley:

**Comment by piotrdrag** [comment]
Polish is up to date, thanks for notifying!

**Comment by lyubomirv** [comment]
Nothing to do for Bulgarian. :)

**Comment by whot** [comment]
no changes needed for german

**Comment by Funeoz** [comment]
French translations have been updated: https://github.com/libratbag/piper/pull/519

**Comment by dastier** [comment]
Looks like Belarusian is also up to date.

**Comment by stephanlachnit** [comment]
Thanks for your contributions, new release is tagged.

**Comment by Hjdskes** [comment]
@stephanlachnit Could you stop tagging me for translations? I no longer have the time to update them and I don't want to hold you up with issues like this one.

**Comment by stephanlachnit** [comment]
> @stephanlachnit Could you stop tagging me for translations? I no longer have the time to update them and I don't want to hold you up with issues like this one.

Sure, no problem.
